# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midepa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
