# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midepa', '0002_auto_20170220_1145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serivicio',
            new_name='Servicio',
        ),
    ]
