# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midepa', '0004_auto_20170222_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condomino', to='midepa.Condominio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='midepa.Presupuesto'),
        ),
    ]
