# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midepa', '0005_auto_20170222_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='midepa.Presupuesto'),
        ),
    ]
