# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midepa', '0007_auto_20170222_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
